---
- name: Install packages for Postgres
  become: yes
  apt: name={{ packages }} state=present update_cache=yes
  vars:
    packages:
      - postgresql
      - python-psycopg2
      - python3-psycopg2

- name: Install Postgis extension for Ubuntu 18.04
  become: yes
  package: name=postgis state=present
  when: postgres_postgis and ansible_distribution_major_version == "18"

- name: Install Postgis extension for Ubuntu 16.04
  become: yes
  package: name={{ packages }} state=present
  vars:
    packages:
      - postgresql-9.5-postgis-2.2
      - postgis

  when: postgres_postgis and ansible_distribution_major_version == "16"

- name: Install Postgis extension for Ubuntu 14.04
  become: yes
  package: name={{ packages }} state=present
  vars:
    packages:
      - postgresql-9.3-postgis-2.1
      - postgis
  when: postgres_postgis and ansible_distribution_major_version == "14"

- name: Install Postgis extension for Debian 9
  become: yes
  package: name=postgis state=present
  when: postgres_postgis and ansible_distribution_major_version == "9"

- name: Install HSTORE extension for Ubuntu 14.04
  become: yes
  package: name=postgresql-contrib-9.3 state=present
  when: postgres_hstore and ansible_distribution_major_version == "14"

- name: Install hstore extension for Ubuntu 16.04
  become: yes
  package: name=postgresql-contrib-9.5 state=present
  when: postgres_postgis and ansible_distribution_major_version == "16"
