---
- name: Ensure fi_FI.UTF-8 locale exists
  locale_gen: name=fi_FI.UTF-8 state=present

- import_tasks: install.yml
  when: postgres_install_engine

- import_tasks: create_db.yml
  when: postgres_create_db

- import_tasks: preload_dump.yml
  when: postgres_preload_data
