---
- name: Ensure fi_FI.UTF-8 locale exists
  locale_gen: name=fi_FI.UTF-8 state=present

- name: Install psycopg2 globally for postgres management
  become: yes
  apt: name={{ packages }} state=present update_cache=yes
  vars:
    packages:
      - python-psycopg2
      - python3-psycopg2

- import_tasks: migration_common.yml

- import_tasks: install.yml
  when: postgres_install_engine

- import_tasks: create_db.yml
  when: postgres_create_db

- import_tasks: preload_dump.yml
