---
- name: Apply SQL dump
  postgresql_db:
    login_user: "{{ postgres_user }}{{ postgres_vhost|default() }}"
    login_password: "{{ postgres_pass }}"
    login_host: "{{ postgres_host | default('localhost') }}"
    name: "{{ postgres_dbname }}"
    state: restore
    target: "{{ dest_temp_data.path }}/{{postgres_dbname}}.sql"
  when: postgres_dump_available is defined and postgres_dump_available is success

- name: Remove the temporary directory from destination host
  become: no
  file:
    path: "{{ dest_temp_data.path }}"
    state: absent
  when: dest_temp_data.path is defined
